name: alphaselect-premier-f
region: sgp

databases:
  - name: postgres-db
    engine: PG
    version: "16"
    production: true

  - name: redis-cache
    engine: REDIS
    version: "7"
    production: true

services:
  - name: backend
    github:
      repo: JonazWong/AlphaSelect-Premier-F
      branch: main
      deploy_on_push: false
    source_dir: backend
    dockerfile_path: Dockerfile
    http_port: 8000
    instance_count: 2
    instance_size_slug: professional-xs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: MEXC_API_KEY
        scope: RUN_TIME
        value: ${MEXC_API_KEY}
      - key: MEXC_SECRET_KEY
        scope: RUN_TIME
        value: ${MEXC_SECRET_KEY}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: MEXC_CONTRACT_BASE_URL
        scope: RUN_TIME
        value: "https://contract.mexc.com"
      - key: MEXC_SPOT_BASE_URL
        scope: RUN_TIME
        value: "https://api.mexc.com"
      - key: AI_MODEL_DIR
        scope: RUN_TIME
        value: "/app/ai_models"
    health_check:
      http_path: /api/v1/health

  - name: frontend
    github:
      repo: JonazWong/AlphaSelect-Premier-F
      branch: main
      deploy_on_push: false
    source_dir: frontend
    dockerfile_path: Dockerfile
    http_port: 3000
    instance_count: 2
    instance_size_slug: basic-xxs
    envs:
      - key: NEXT_PUBLIC_API_URL
        scope: RUN_AND_BUILD_TIME
        value: ${backend.PUBLIC_URL}
      - key: NEXT_PUBLIC_WS_URL
        scope: RUN_AND_BUILD_TIME
        value: ${backend.PUBLIC_URL}
    routes:
      - path: /
    health_check:
      http_path: /health

  - name: celery-worker
    github:
      repo: JonazWong/AlphaSelect-Premier-F
      branch: main
      deploy_on_push: false
    source_dir: backend
    dockerfile_path: Dockerfile
    instance_count: 1
    instance_size_slug: basic-xs
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: REDIS_URL
        scope: RUN_TIME
        type: SECRET
      - key: MEXC_API_KEY
        scope: RUN_TIME
        value: ${MEXC_API_KEY}
      - key: MEXC_SECRET_KEY
        scope: RUN_TIME
        value: ${MEXC_SECRET_KEY}
      - key: SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AI_MODEL_DIR
        scope: RUN_TIME
        value: "/app/ai_models"
    run_command: "celery -A app.tasks.celery_app worker --loglevel=info"
